# Write a custom iterator class that returns numbers from 1 to n
"""Iimplement a custom iterator that yields numbers from 1 to n"""

from __future__ import annotations


class OneToNIterator:
    """iterate over integers from 1 through a given limit"""

    def __init__(self, limit: int) -> None:
        """Store the iteration limit"""

        self.limit = limit
        self.current = 1

    def __iter__(self) -> OneToNIterator:
        """return the iterator instance"""

        return self

    def __next__(self) -> int:
        """return the next integer or stop iteration"""

        if self.current > self.limit:
            raise StopIteration

        value = self.current
        self.current += 1
        return value


def collect_numbers(limit: int) -> list[int]:
    """collect all numbers generated by onetoniterator"""

    return list(OneToNIterator(limit))


def main() -> None:
    """show the custom iterator class"""

    print(collect_numbers(5))


if __name__ == "__main__":
    main()