"""add_missing_columns

Revision ID: c4cd710b3c39
Revises: 75cdce6f8106
Create Date: 2026-07-05 17:23:38.431361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cd710b3c39'
down_revision = '75cdce6f8106'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participation_requests', sa.Column('participant_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participation_requests', 'participant_count')
    # ### end Alembic commands ###